### ISSUE TITLE
关于消息模型时间的类型

### ISSUE THREAD

**Issue by he0119** [MeetWq/nonebot-plugin-chatrecorder#1]
说起来既然用了 ORM，为什么不直接用 [datetime](https://docs.sqlalchemy.org/en/14/core/type_basics.html?highlight=timestamp#sqlalchemy.types.DateTime) 呢😂
https://github.com/MeetWq/nonebot-plugin-chatrecorder/blob/a176ca0a10678f4203bd440684803e953f2d350f/nonebot_plugin_chatrecorder/model.py#L13

**Comment by he0119** [comment]
对了，感觉如果同时多存一个 plaintext 会比较方便。我的那个词云也不需要 Message，这样可以提升速度。

**Comment by MeetWq** [comment]
改了，加了个 plain_text 参数

**Comment by he0119** [comment]
大过年的，辛苦了
